spring:
  data:
    mongodb:
      uri: mongodb+srv://vipopi1997:JiJqgunzxS8n9QDm@vppcluster.bhaevgv.mongodb.net/trips-db?retryWrites=true&w=majority
  mvc:
    converters:
      preferred-json-mapper: gson
server:
  port: 9999